### PR TITLE
Added enum value mapping logic and build and release pipeline

### PR DESCRIPTION
**Pull request by HenkKin**
I used AutoMapper.Extensions.ExpressionMapping as an example for build and release pipeline. Please have a look at the api keys in the appveyor file.

This version is using AutoMapper 9.1.0-ci-* from myget automapperdev. When AutoMapper 9.1.0 is released, then this can be changed.

### CODE REVIEW

**Comment by lbargaoanu** [comment]
I've already added the AM snk. I see you added two other. You should enable SourceLink.

**Comment by HenkKin** [comment]
> I've already added the AM snk. I see you added two other. You should enable SourceLink.

Sorry, i did not see it, i have corrected it now. Also added SourceLink

**Comment by jbogard** [comment]
https://ci.appveyor.com/project/jbogard/automapper-extensions-enummapping

**Comment by HenkKin** [comment]
> https://ci.appveyor.com/project/jbogard/automapper-extensions-enummapping

Please can you provide the "Branch sample markdown code" under tab "Badges" from appveyor settings page? Then the badge of the master build can be shown in the repository.

**Pull request merged**
